apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-dummy
  namespace: duma
  labels:
    app: canary-dummy
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary-dummy
      pipecd.dev/variant: primary
  template:
    metadata:
      labels:
        app: canary-dummy
        pipecd.dev/variant: primary
    spec:
      containers:
      - name: helloworld
        image: ductn4/green-rain:v1.0.1
        ports:
        - containerPort: 3000
