apiVersion: v1
kind: Service
metadata:
  name: canary-dummy
  namespace: duma
spec:
  selector:
    app: canary-dummy
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
